#!/usr/bin/env bash

set -euo pipefail

CORE="${AZEROTHCORE_ROOT:-$HOME/azerothcore}"
SETUP="${AZEROTHCORE_SETUP_ROOT:-$HOME/azerothcore-setup}"
OUT="$SETUP/docs/project/generated/ENVIRONMENT.md"

die() {
    echo "ERROR: $*" >&2
    exit 1
}

is_git_repo() {
    git -C "$1" rev-parse --is-inside-work-tree >/dev/null 2>&1
}

repo_info() {
    local name="$1"
    local path="$2"

    local branch
    local commit
    local remote
    local dirty
    local changed_count

    branch="$(git -C "$path" symbolic-ref --quiet --short HEAD 2>/dev/null || printf 'DETACHED')"
    commit="$(git -C "$path" rev-parse HEAD)"
    remote="$(git -C "$path" remote get-url origin 2>/dev/null || printf 'none')"

    changed_count="$(
        git -C "$path" status --porcelain=v1 --untracked-files=normal \
            | wc -l
    )"

    if [[ "$changed_count" -eq 0 ]]; then
        dirty="clean"
    else
        dirty="DIRTY ($changed_count paths)"
    fi

    cat <<REPO
### $name

- Path: \`$path\`
- Branch: \`$branch\`
- Commit: \`$commit\`
- Origin: \`$remote\`
- Working tree: **$dirty**

REPO
}

[[ -d "$CORE" ]] || die "AzerothCore directory not found: $CORE"
[[ -d "$SETUP" ]] || die "Setup directory not found: $SETUP"

is_git_repo "$CORE" ||
    die "AzerothCore path is not a Git working tree: $CORE"

is_git_repo "$SETUP" ||
    die "Setup path is not a Git working tree: $SETUP"

mkdir -p "$(dirname "$OUT")"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
    cat <<HEADER
# Generated Environment

> Generated automatically by \`scripts/agent/refresh-environment.sh\`.
> Do not edit this file manually.
> Do not treat values from an older copy as authoritative.

- Generated: \`$(date --iso-8601=seconds)\`
- Host: \`$(hostname)\`
- User: \`$(id -un)\`

## Primary repositories

HEADER

    repo_info "AzerothCore" "$CORE"
    repo_info "azerothcore-setup" "$SETUP"

    echo "## Independent module repositories"
    echo

    module_count=0

    if [[ -d "$CORE/modules" ]]; then
        while IFS= read -r -d '' module; do
            module_root="$(
                git -C "$module" rev-parse --show-toplevel 2>/dev/null || true
            )"

            [[ -n "$module_root" ]] || continue

            if [[ "$(realpath "$module_root")" == "$(realpath "$module")" ]]; then
                repo_info "$(basename "$module")" "$module"
                module_count=$((module_count + 1))
            fi
        done < <(
            find "$CORE/modules" \
                -mindepth 1 \
                -maxdepth 1 \
                -type d \
                -print0 \
                | sort -z
        )
    fi

    if [[ "$module_count" -eq 0 ]]; then
        echo "_No independent module Git repositories detected._"
        echo
    fi

    echo "## Local layout"
    echo

    for path in \
        "$CORE/build" \
        "$CORE/env" \
        "$CORE/env/dist" \
        "$CORE/env/dist/bin"
    do
        if [[ -e "$path" ]]; then
            echo "- Present: \`$path\`"
        else
            echo "- Missing: \`$path\`"
        fi
    done

    echo
    echo "## Installed server binaries"
    echo

    for binary in authserver worldserver; do
        binary_path="$CORE/env/dist/bin/$binary"

        if [[ -x "$binary_path" ]]; then
            echo "- \`$binary\`: \`$binary_path\`"
        else
            echo "- \`$binary\`: not detected at expected path"
        fi
    done

    echo
    echo "## Custom SQL inventory"
    echo

    SQL_ROOT="$SETUP/data/sql/custom"

    if [[ -d "$SQL_ROOT" ]]; then
        sql_count="$(
            find "$SQL_ROOT" -type f -name '*.sql' | wc -l
        )"

        echo "- SQL root: \`$SQL_ROOT\`"
        echo "- SQL files: \`$sql_count\`"
        echo

        if [[ "$sql_count" -gt 0 ]]; then
            find "$SQL_ROOT" \
                -type f \
                -name '*.sql' \
                -printf '%P\n' \
                | sort \
                | sed 's/^/- `/' \
                | sed 's/$/`/'
        fi
    else
        echo "_Custom SQL directory not found._"
    fi

    echo
    echo "## Working-tree warnings"
    echo

    core_changes="$(
        git -C "$CORE" status --porcelain=v1 --untracked-files=normal
    )"

    setup_changes="$(
        git -C "$SETUP" status --porcelain=v1 --untracked-files=normal
    )"

    if [[ -z "$core_changes" ]]; then
        echo "- AzerothCore working tree is clean."
    else
        echo "- **AzerothCore working tree has pending changes.**"
    fi

    if [[ -z "$setup_changes" ]]; then
        echo "- azerothcore-setup working tree is clean."
    else
        echo "- **azerothcore-setup working tree has pending changes.**"
    fi

    cat <<FOOTER

## Interpretation

This document records mechanically detectable facts only.

Architectural meaning, project decisions and task progress belong in the
durable documentation and execution plans, not here.
FOOTER

} > "$TMP"

mv "$TMP" "$OUT"
trap - EXIT

echo "Environment state refreshed:"
echo "$OUT"
